home/urls.py
from django.urls import path
from . import views
from .views import WelcomeView, PostView, CategoryView, RecipeView

app_name = 'home'

urlpatterns = [
        path('', WelcomeView.as_view(), name='welcome'),
        path('post/<int:pk>', PostView.as_view(), name='post'),
        path('category/<int:pk>', CategoryView.as_view(), name='category'),
        path('recipe', RecipeView.as_view(), name='recipe'),
        #path('', .as_view(), name=''),
        ]

myblog/urls.py
from django.contrib import admin
from django.urls import include, path
from home.views import WelcomeView, PostView, CategoryView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('home/', include('home.urls')),
    path('admin/', admin.site.urls),
    #path('', include('.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.urls import reverse

# Create your models here.

class Category(models.Model):
    name=models.CharField(max_length=200)
    class Meta:
        verbose_name='Category'
        verbose_name_plural='Categories'
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('home:category', kwargs={'name': self.name})

class Post(models.Model):
    title=models.CharField(max_length=255, verbose_name='Title')
    body=models.TextField()
    pub_date=models.DateTimeField(auto_now_add=True)
    slug=models.SlugField()
    category=models.ForeignKey(Category, verbose_name='Category', on_delete=models.CASCADE)
     
    class Meta:
        verbose_name='Post'
        verbose_name_plural='Posts'
        ordering=['pub_date']

    def __str__(self):
        return self.title

    def get_cat_list(self):
        return Post.objects.filter(category__name=self.name)
        k = self.category

    def get_absolute_url(self):
        return reverse('home:post', args=[self.pk])

class Recipe(Post):
    ingredients=models.TextField()
    method=Post.body
    serves=models.PositiveSmallIntegerField()
    time_to_make=models.PositiveSmallIntegerField()
    

home/views.py
from django.shortcuts import render, get_list_or_404, get_object_or_404
from django.http import HttpResponse
from django.views.generic import ListView, DetailView
from .models import Post, Category, Recipe 
# Create your views here.

class RecipeView(DetailView):
    model=Recipe
    template_name='home/recipe.html'
    def get_qeuryset(self):
        return Recipe.objects.all()

class WelcomeView(ListView):                                                            
    queryset = Post.objects.all()  #order_by('-pub_date')                                
    template_name = 'home/welcome.html' 

class PostView(DetailView):
    model = Post
    template_name = 'home/post.html'

class CategoryView(ListView):
    model=Post
    template_name='home/category.html'
    #The methods below were discovered at https://www.youtube.com/watch?v=uyTdSdOWHHk at 11:22, Credit to Emmanuel Okiche.

    def get_queryset(self): 
        self.category=get_object_or_404(Category, pk=self.kwargs['pk'])
        return Post.objects.filter(category=self.category)

    def get_context_data(self, **kwargs):
        context=super(CategoryView, self).get_context_data(**kwargs)
        context['category']=self.category
        return context

def cat_list(request):
    # category loops on navbar
    cat_list=Category.objects.filter()
    context = {"cat_list": cat_list,}
    return context

home/templates/home/category.html
{% extends 'home/core.html' %}

{% block content %}
	<div>
	<h1>{{ category.name }}</h1>
	</div>
	{% for post in object_list %}
	<div>
		<h3><a href="{% url 'home:post' post.pk%}">{{ post.title }}</a> </h3>
	{% endfor %}

	  <hr>
                   <a href="{% url 'home:welcome'  %}"class="btn btn-primary">Back</a>

{% endblock %}

home/templates/home/core.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
        {% load static %}
        <link href="{% static 'home/style.css' %}" type="text/css" rel="stylesheet"/>
	<title>
        {% block title %}
	Dash Paulson
        {% endblock %}
    	</title>
  </head>
<style>
	:root{--mono-font: San Francisco Mono, Monaco, "Consolas", "Lucida Console",
    	"DejaVu Sans Mono", "Bitstream Vera Sans Mono", monospace;	
	--sans-font: -apple-system, BlinkMacSystemFont, "avenir next", avenir,
    	helvetica, "helvetica neue", ubuntu, roboto, noto, "segoe ui", arial,
    sans-serif
	}
	body{ margin:0 auto;-webkit-font-smoothing:antialiased;text-rendering:optimizeLegibility;line-height:1.6;font-size:1rem;font-family:var(--sans-font)}.only-print{display:none}
	a{color:#000;text-decoration-skip-ink:auto;text-decoration:underline}
	a:visited{color:#333}
	ul{margin:1rem 0}
	ul ul{margin:0}
	.small,small{font-size:14px}
	body,h1 a{color:#111}
	h1,h2{margin-bottom:.5rem;line-height:1.25;font-weight:600}
	h1{font-size:32px;letter-spacing:.004em}
	h2{font-size:1.5rem;letter-spacing:.009em}
	.limiter{max-width:640px;padding-left:20px;padding-right:20px;margin-left:auto;margin-right:auto}
	.pad2y{padding-top:9px;padding-bottom:20px}
	.writing{display:grid;grid-column-gap:5px;grid-row-gap:5px;grid-template-columns:1fr min-content}
	.writing a{font-weight:500;letter-spacing:-.015em}
	.writing>div{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
	.writing time{padding-right:.25em;color:#333;font-variant-numeric:tabular-nums;letter-spacing:-.012em;white-space:pre}
	@media screen and (max-width:640px){.limiter{width:auto}
	.writing{grid-template-columns:1fr;grid-row-gap:0}
	.writing div{white-space:normal}
	.writing time{padding-bottom:20px}}
	@media screen and (min-width:640px){.nu a{text-decoration:none}.nu 
	a:hover{text-decoration:underline}}
	@media screen and (max-width:1024px){.header-rap{border-bottom:1px solid #000;padding-bottom:20px}}
	@media screen and (min-width:1025px){.header{position:absolute;top:40px;right:50%;margin-right:340px!important;letter-spacing:-.009em}
	.content h1:first-child{margin-top:0}}
	@media print{.no-print{display:none}.only-print{display:block}body{margin:0}
	.limiter{max-width:100%!important;margin:0!important;padding:0!important}}.m{color:#007f7f}.s{color:#d01040}
</style>

  <body>
	 <div class="pad2y" style="position:relative">
	  <nav class="header-wrap">
                <div class="header nu limiter no-print">
			<h1 style="line-height:1.6;font-size:1rem;margin:0 0 0.25em 0;">Dashiell<br> Paulson</h1>
                        <ul style="list-style:none;padding:0;margin:0;">
				{% for category in cat_list %}
				<li><a href="{% url 'home:category' category.pk %}">{{ category.name }}</a>
                                </li>
				{% endfor %}
                        </ul>
                </div>
        </nav>
       </div>
       <div class="pad2y limiter content">
<div class="container">
          {% block content %}

          {% endblock %}
        </div>
       </div>

 </body>
</html>

home/templates/home/post.html
{% extends 'home/core.html' %}

{% block title %}{{ post.title }}{% endblock %}
        {% block content %}
                <h1>{{ post.title }}</h1>
                <small>Published: {{ post.pub_date }}</small><br/>
                <small>Category: {{ post.category }}</small><br/>
                <hr>
                <br/>
                   {{ post.body }}
                        <hr>
                   <a href="{% url 'home:welcome'  %}"class="btn btn-primary">Back</a>

        {% endblock %}

home/templates/home/welcome.html
{% extends 'home/core.html' %}
{% block content %}
                <h1>Welcome</h1>
                <h2>The key to success</br>is to never give up</h2>
                <hr>
                <ul>
                    {% for post in object_list %}
		    <li><a href="{% url 'home:post' post.pk %}">{{ post.title }}</a>
                        {{ post.pub_date }}
                   </li>
                    {% endfor %}

{% endblock %}